In [214]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import scipy
import numpy as np

In [215]:
df_train = pd.read_csv("train.csv")
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [216]:
df_test = pd.read_csv("test.csv")
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [217]:
EmCV = CountVectorizer()

X = df_train[["Pclass", "SibSp", "Fare", "Parch", "Age"]].fillna(171717)
# X_Embarked =  EmCV.fit_transform(df_train["Embarked"].fillna("None"))
X = np.hstack([X.values, (df_train["Sex"].values == "male").reshape(X.shape[0], 1) * 1])
X

array([[3.00000e+00, 1.00000e+00, 7.25000e+00, 0.00000e+00, 2.20000e+01,
        1.00000e+00],
       [1.00000e+00, 1.00000e+00, 7.12833e+01, 0.00000e+00, 3.80000e+01,
        0.00000e+00],
       [3.00000e+00, 0.00000e+00, 7.92500e+00, 0.00000e+00, 2.60000e+01,
        0.00000e+00],
       ...,
       [3.00000e+00, 1.00000e+00, 2.34500e+01, 2.00000e+00, 1.71717e+05,
        0.00000e+00],
       [1.00000e+00, 0.00000e+00, 3.00000e+01, 0.00000e+00, 2.60000e+01,
        1.00000e+00],
       [3.00000e+00, 0.00000e+00, 7.75000e+00, 0.00000e+00, 3.20000e+01,
        1.00000e+00]])

In [218]:
from sklearn.ensemble import RandomForestClassifier
y = df_train["Survived"].values
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [219]:
LR = GradientBoostingClassifier()
LR.fit(X, y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [220]:
X_test = df_test[["Pclass", "SibSp", "Fare", "Parch", "Age"]].fillna(171717)
#X_test_Embarked =  EmCV.transform(df_test["Embarked"].fillna("None"))
X_test = np.hstack([X_test.values, (df_test["Sex"].values == "male").reshape(X_test.shape[0], 1) * 1])
X_test

array([[3.00000e+00, 0.00000e+00, 7.82920e+00, 0.00000e+00, 3.45000e+01,
        1.00000e+00],
       [3.00000e+00, 1.00000e+00, 7.00000e+00, 0.00000e+00, 4.70000e+01,
        0.00000e+00],
       [2.00000e+00, 0.00000e+00, 9.68750e+00, 0.00000e+00, 6.20000e+01,
        1.00000e+00],
       ...,
       [3.00000e+00, 0.00000e+00, 7.25000e+00, 0.00000e+00, 3.85000e+01,
        1.00000e+00],
       [3.00000e+00, 0.00000e+00, 8.05000e+00, 0.00000e+00, 1.71717e+05,
        1.00000e+00],
       [3.00000e+00, 1.00000e+00, 2.23583e+01, 1.00000e+00, 1.71717e+05,
        1.00000e+00]])

In [221]:
predicted = LR.predict(X_test)
predicted

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [222]:
df_pred = pd.DataFrame()

df_pred["PassengerId"] = df_test["PassengerId"]
df_pred["Survived"] = predicted
df_pred.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         0

In [223]:
df_pred.to_csv("predicted.csv", index=False)

In [225]:
df_pred.head(10)

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         0
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0